docs_dir: .

# Project information
site_name: SuperS2
site_url: https://ipl-uv.github.io/supers2/
site_author: IPL-UV
site_description: A Python package for efficient processing of cubic earth observation (EO) data.


# Repository
repo_url: https://github.com/IPL-UV/supers2
repo_name: supers2
use_directory_urls: false

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: '#d49f0c'
      accent: '#d49f0c'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: ./assets/images/logo_circular_sr.png
  favicon: ./assets/images/logo_circular_sr.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide   


nav:
  - Home: 
    - README.md
    - Contributing: CONTRIBUTING.md
    - Changelog: CHANGELOG.md
    - Code of conduct: CODE_OF_CONDUCT.md
  # - Functions: 
  #   - ./docs/FUNCTIONS.md
  #   - Query metadata: ./docs/Functions/query_metadata.md
  #   - Process Image: ./docs/Functions/process_image.md
  #   - Download Data: ./docs/Functions/download_data.md
  # - Processes: 
  #   - ./docs/PROCESSES.md
  #   - Recursion: ./docs/Process/recursion.md
  #   - Concurrency: ./docs/Process/concurrency.md
  #   - Parallelism: ./docs/Process/parallelism.md
  #   - Difference: ./docs/Process/difference.md
  # - Comparation:
  #   - ./docs/COMPARATION.md
  #   - Get: ./docs/Comparation/eedatagetPixels.md
  #   - Compute: ./docs/Comparation/eedatacomputePixels.md
  #   - Comparison: ./docs/Comparation/comparison.md
  #   - Conclusion: ./docs/Comparation/conclusion.md

# Plugins
plugins:
  - search
  - same-dir
  - mkdocstrings 
  - awesome-pages

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist

extra_css:
  - assets/style.css
extra_javascript:
  - assets/js.js
